# do_release.yaml
name: do_release
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'
permissions:
  contents: write # Allow workflow to create releases
jobs:
  do_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_github_action_code
        uses: actions/checkout@v4
      - name: create_release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Above is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            Changes in this Release
            - First change
            - Second change
