# do_release.yaml
name: do_release
on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'     
        required: true              
        type: choice
        options:
          - 'v2.0.0'
          - 'v2.1.0'
          - 'v2.2.0'
          - 'Other'
permissions:
  contents: write # Allow workflow to create releases
jobs:
  do_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_github_action_code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}
      - name: create_release
        if: github.event.inputs.tag_name != 'Other'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Above is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Release ${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
          body: 'Release ${{ github.event.inputs.tag_name }}'
          
